### PR TITLE
Added https support

### PR DESCRIPTION
**Pull request by kristjanmik**
I added a regex that supports https as well :) 
Cheers!

### CODE REVIEW

**Comment by kristjanmik** [comment]
I also added some tests to the output

**Comment by leecrossley** [comment]
You can't use a custom domain name with GitHub pages and HTTPS? Correct me if I'm wrong?

**Comment by kristjanmik** [comment]
It can be done via Cloudflare and similar services. https://kristjanmik.is/ is a hexo blog, hostet by Github pages and has https only enabled using Cloudflare. Therefore it seems usefull to add it to this package :)

**Comment by leecrossley** [comment]
Ah yes, good point :)

**Pull request merged**
